### ISSUE TITLE
FastBoot support

### ISSUE THREAD

**Issue by mirague** [MindscapeHQ/ember-cli-raygun#14]
When using FastBoot the bower extension should not be imported.

NodeJS throws below error because of it:
```
ReferenceError: document is not defined
    at Object._private.readCookie (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:73910:34)
    at ensureUser (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:74105:37)
    at Object.init (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:73683:13)
    at /Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:77878:16
    at exports.default (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:77905:9)
    at Object.initialize (/Users/melvin/Projects/bazaar/dist/fastboot/bazaar.js:973:71)
    at /Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:16073:23
    at Vertices.each (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:14140:13)
    at Vertices.topsort (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:14107:14)
    at DAG.topsort (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:14052:24)
    at Class._runInitializer (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:16101:13)
    at Class.runInitializers (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:16062:12)
    at Class._bootSync (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:15260:14)
    at Class.boot (/Users/melvin/Projects/bazaar/dist/fastboot/vendor.js:15227:14)
    at EmberApp.buildAppInstance (/Users/melvin/Projects/bazaar/node_modules/fastboot/src/ember-app.js:211:21)
    at EmberApp.visitRoute (/Users/melvin/Projects/bazaar/node_modules/fastboot/src/ember-app.js:234:17)
    at EmberApp.visit (/Users/melvin/Projects/bazaar/node_modules/fastboot/src/ember-app.js:309:17)
    at FastBoot.visit (/Users/melvin/Projects/bazaar/node_modules/fastboot/src/index.js:79:22)
    at /Users/melvin/Projects/bazaar/node_modules/fastboot-express-middleware/src/index.js:32:14
    at Layer.handle [as handle_request] (/Users/melvin/Projects/bazaar/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/melvin/Projects/bazaar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/melvin/Projects/bazaar/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/melvin/Projects/bazaar/node_modules/express/lib/router/layer.js:95:5)
    at /Users/melvin/Projects/bazaar/node_modules/express/lib/router/index.js:281:22
    at param (/Users/melvin/Projects/bazaar/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/melvin/Projects/bazaar/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/melvin/Projects/bazaar/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/melvin/Projects/bazaar/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/melvin/Projects/bazaar/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/Users/melvin/Projects/bazaar/node_modules/send/index.js:282:17)
    at SendStream.onStatError (/Users/melvin/Projects/bazaar/node_modules/send/index.js:433:12)
    at next (/Users/melvin/Projects/bazaar/node_modules/send/index.js:743:16)
    at onstat (/Users/melvin/Projects/bazaar/node_modules/send/index.js:732:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

The import can be made conditionally by checking for `` as such:
```
if (!process.env.EMBER_CLI_FASTBOOT) {
  app.import('bower_components/.../dist/raygun.js');
}
```

Ideas?

**Comment by nikz** [comment]
Hi @mirague, realise this issue is quite old at this point but we've now rewritten the add-on and there's no longer a bower dependency 👍
